apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-modeling
spec:
  selector:
    matchLabels:
      app: python
  replicas: 1
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: data-modeling
        imagePullPolicy: Always
        image: sgarandomerror/datamodeling:random
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: datamodeling-persistent-storage
          mountPath: /plots
      volumes:
         - name: datamodeling-persistent-storage
           persistentVolumeClaim:
             claimName: datamodeling-pv-claim

