apiVersion: v1
kind: Service
metadata:
  name: data-modeling-service
  labels:
    app: data-modeling
spec:
  ports:
  - port: 8077
    targetPort: 8077
    nodePort: 30534
    # protocol: HTTP
  selector:
    app: data-modeling
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-modeling-deployment-l0.1
  labels:
    app: data-modeling
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-modeling
  template:
    metadata:
      labels:
        app: data-modeling
    spec:
      containers:
      - name: data-modeling
        image: sgarandomerror/data-modeling:l0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8077
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-modeling-deployment-l0.2
  labels:
    app: data-modeling
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-modeling
  template:
    metadata:
      labels:
        app: data-modeling
    spec:
      containers:
      - name: data-modeling
        image: sgarandomerror/data-modeling:l0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8077	