apiVersion: v1
kind: Service
metadata:
  name: session-store-service-linkerd
  labels:
    app: session-store
spec:
  selector:
    app: session-store
  type: NodePort
  ports:
  - port: 8088
    targetPort: 8088
    nodePort: 30535
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-store-deployment-l0.1
  labels:
    app: session-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session-store
  template:
    metadata:
      labels:
        app: session-store
    spec:
      containers:
      - name: session-store
        image: sgarandomerror/sessionstore:l0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8088	
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-store-deployment-l0.2
  labels:
    app: session-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session-store
  template:
    metadata:
      labels:
        app: session-store
    spec:
      containers:
      - name: session-store
        image: sgarandomerror/session-store:l0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8088		
