apiVersion: v1
kind: Service
metadata:
  name: session-management-service  
spec:
 selector:
    app: node
 type: NodePort
 ports:
  - targetPort: 8082
    port: 8082
    nodePort: 30333
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sessionmanagement
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: sessionmanagement
        imagePullPolicy: Always
        image: sgarandomerror/sessionmanagement:random
        ports:
        - containerPort: 8082