apiVersion: v1
kind: Service
metadata:
  name: data-retrieval-service
  labels:
    app: data-retrieval
spec:
  ports:
  - port: 8078
    targetPort: 8078
    nodePort: 30536
    protocol: TCP
  selector:
    app: data-retrieval
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-retrieval-deployment-l0.1
  labels:
    app: data-retrieval
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-retrieval
  template:
    metadata:
      labels:
        app: data-retrieval
    spec:
      containers:
      - name: data-retrieval
        image:  
        imagePullPolicy: Always
        ports:
        - containerPort: 8078
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-retrieval-deployment-l0.2
  labels:
    app: data-retrieval
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-retrieval
  template:
    metadata:
      labels:
        app: data-retrieval
    spec:
      containers:
      - name: data-retrieval
        image: sgarandomerror/data-retrieval:l0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8078