apiVersion: v1
kind: Service
metadata:
  name: session-retrieve-service-linkerd
  labels:
    app: session-retrieve
spec:
  selector:
    app: session-retrieve
  type: NodePort
  ports:
  - port: 8087
    targetPort: 8087
    nodePort: 30533 
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-retrieve-deployment-l0.1
  labels:
    app: session-retrieve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session-retrieve
  template:
    metadata:
      labels:
        app: session-retrieve
    spec:
      containers:
      - name: session-retrieve
        image: sgarandomerror/sessionretrieve:l0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8087	
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-retrieve-deployment-l0.2
  labels:
    app: session-retrieve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session-retrieve
  template:
    metadata:
      labels:
        app: session-retrieve
    spec:
      containers:
      - name: session-retrieve
        image: sgarandomerror/sessionretrieve:l0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8087		