apiVersion: v1
kind: Service
metadata:
  name: ui-api-service  
spec:
 selector:
    app: java-ms
 type: NodePort
 ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30127
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-api
spec:
  selector:
    matchLabels:
      app: java-ms
  replicas: 1
  template:
    metadata:
      labels:
        app: java-ms
    spec:
      containers:
      - name: ui-api
        imagePullPolicy: Always
        image: sgarandomerror/ui-api:random
        ports:
        - containerPort: 8080
  
