apiVersion: v1
kind: Service
metadata:
  name: usermanagement-service
spec:
 selector:
    app: java
 type: NodePort
 ports:
  - targetPort: 8081
    port: 8081
    nodePort: 30555
 selector:
  app: java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement
spec:
  selector:
    matchLabels:
      app: java
  replicas: 1
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: usermanagement
        imagePullPolicy: Always
        image: sgarandomerror/usermanagement:random
        ports:
        - containerPort: 8081
