apiVersion: v1
kind: Service
metadata:
  name: data-retrieval
spec:
 ports:
  - targetPort: 5002
    port: 5002
    
 selector:
  app: python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-retrieval
spec:
  selector:
    matchLabels:
      app: python
  replicas: 1
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: data-retrieval
        imagePullPolicy: Always
        image: sgarandomerror/dataretrieval:random
        ports:
        - containerPort: 5002