apiVersion: v1
kind: PersistentVolume
metadata:
  name: datamodeling-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /plots
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datamodeling-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
