apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-test
spec:   
  type: ClusterIP
  ports:
   - port: 5672
     targetPort: 5672

  selector:
     app: rabbitmq  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        imagePullPolicy: Always
        image: rabbitmq:management
        ports:
        - containerPort: 5672